# Generated by Django 3.2.9 on 2021-11-24 00:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('recommendedYear', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='uploads/courses/', width_field='width_field')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=30)),
                ('lastName', models.CharField(blank=True, max_length=30)),
                ('skill', models.CharField(blank=True, max_length=50, null=True)),
                ('house', models.CharField(blank=True, choices=[('GRYFFINDOR', 'Gryffindor'), ('RAVENCLAW', 'Ravenclaw'), ('HUFFLEPUFF', 'Hufflepuff'), ('SLYTHERIN', 'Slytherin')], default='GRYFFINDOR', max_length=10, null=True)),
                ('currentYear', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
                ('enrollDate', models.DateField()),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='uploads/students/', width_field='width_field')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.enrollment')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
