# Generated by Django 3.2.9 on 2021-11-24 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20211123_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
    ]
