# Generated by Django 3.2.9 on 2021-12-15 20:02

from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('firstName', models.CharField(blank=True, max_length=30)),
                ('lastName', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=students.models.upload_professor_image, width_field='width_field')),
                ('height_field', models.IntegerField(blank=True, default=0, null=True)),
                ('width_field', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
